POST http://localhost:3000/public/auth
Content-Type: application/json

{
  "email": "youpp@126.com",
  "password": "111111"
}

###

GET http://localhost:3000/awesome-comments?page=1&search={content:'lorem ipsum'}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQwMzU3NzYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6NiwiaWF0IjoxNTY0MDMyMTc2fQ.qe9rrsjKJIdASvA9ZHGQy4MdCbGDzeX_-s76x5rP2cY

###

GET http://localhost:3000/awesome-comments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQwMzU3NzYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6NiwiaWF0IjoxNTY0MDMyMTc2fQ.qe9rrsjKJIdASvA9ZHGQy4MdCbGDzeX_-s76x5rP2cY
###

### create awesome comments
POST http://localhost:3000/awesome-comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQwMzU3NzYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6NiwiaWF0IjoxNTY0MDMyMTc2fQ.qe9rrsjKJIdASvA9ZHGQy4MdCbGDzeX_-s76x5rP2cY

{
  "content": "lorem ipsum dolor sit amet",
  "more": {
    "reference": "https://github.com/buuug7",
    "npm": "https://npmjs.com/buuug7"
  }
}

### update awesome comment

PUT http://localhost:3000/awesome-comments/18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQwMzU3NzYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6NiwiaWF0IjoxNTY0MDMyMTc2fQ.qe9rrsjKJIdASvA9ZHGQy4MdCbGDzeX_-s76x5rP2cY

{
  "content": "such more useful clean my home"
}

###

### Delete the awesome comment
DELETE http://localhost:3000/awesome-comments/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQwMzU3NzYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6NiwiaWF0IjoxNTY0MDMyMTc2fQ.qe9rrsjKJIdASvA9ZHGQy4MdCbGDzeX_-s76x5rP2cY

###
