
### auth user
POST http://localhost:3000/public/auth
Content-Type: application/json

{
  "email": "youpp@126.com",
  "password": "111111"
}

### list soup
GET http://localhost:3000/soups?currentPage=1&search_user=buuug7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQzMTgzMDYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIzMTkwNn0.GHQWFaQ2gX_Ggb88DUj9BApNPJcGOiKqXUJpaiVER1U

### get one soup
GET http://localhost:3000/soups/1111
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQzMTgzMDYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIzMTkwNn0.GHQWFaQ2gX_Ggb88DUj9BApNPJcGOiKqXUJpaiVER1U

### create soup
POST http://localhost:3000/soups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQzMTgzMDYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIzMTkwNn0.GHQWFaQ2gX_Ggb88DUj9BApNPJcGOiKqXUJpaiVER1U

{
  "content": "然而，TypeScript会认为这段代码可能存在bug。 对象字面量会被特殊对待而且会经过额外属性检查，当将它们赋值给变量或作为参数传递的时候。 如果一个对象字面量存在任何“目标类型”不包含的属性时，你会得到一个错误。",
  "more": {
    "reference": "https://github.com/buuug7",
    "npm": "https://npmjs.com/buuug7"
  }
}

### update soup

PUT http://localhost:3000/soups/143434
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQzMTgzMDYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIzMTkwNn0.GHQWFaQ2gX_Ggb88DUj9BApNPJcGOiKqXUJpaiVER1U

{
  "content": "such more useful clean my home"
}

### Delete the soup
DELETE http://localhost:3000/soups/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQzMTgzMDYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIzMTkwNn0.GHQWFaQ2gX_Ggb88DUj9BApNPJcGOiKqXUJpaiVER1U

### star a soup
POST http://localhost:3000/soups/6/star
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQzMTgzMDYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIzMTkwNn0.GHQWFaQ2gX_Ggb88DUj9BApNPJcGOiKqXUJpaiVER1U

### unstar a soup
POST http://localhost:3000/soups/3/unstar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQzMTgzMDYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIzMTkwNn0.GHQWFaQ2gX_Ggb88DUj9BApNPJcGOiKqXUJpaiVER1U

### get soup star count
GET http://localhost:3000/soups/3/starcount
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQzMTgzMDYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIzMTkwNn0.GHQWFaQ2gX_Ggb88DUj9BApNPJcGOiKqXUJpaiVER1U

### get user star soups
GET http://localhost:3000/users/11/starSoups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQzMTgzMDYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIzMTkwNn0.GHQWFaQ2gX_Ggb88DUj9BApNPJcGOiKqXUJpaiVER1U

### test
GET http://localhost:3000/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQzMTgzMDYsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIzMTkwNn0.GHQWFaQ2gX_Ggb88DUj9BApNPJcGOiKqXUJpaiVER1U

###
