
### auth user
POST http://localhost:3000/public/auth
Content-Type: application/json

{
  "email": "youpp@126.com",
  "password": "111111"
}

### list soup
GET http://localhost:3000/soups?page=1&search={content:'lorem ipsum'}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQyMTYyNDgsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIxMjY0OH0.7aQjbek_DdZXBOmYqj0QGRbOluYNp-1WCGYRLc7ApZ0

### get one soup
GET http://localhost:3000/soups/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQyMTYyNDgsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIxMjY0OH0.7aQjbek_DdZXBOmYqj0QGRbOluYNp-1WCGYRLc7ApZ0

### create soup
POST http://localhost:3000/soups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQyMTYyNDgsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIxMjY0OH0.7aQjbek_DdZXBOmYqj0QGRbOluYNp-1WCGYRLc7ApZ0

{
  "content": "lorem ipsum dolor sit amet",
  "more": {
    "reference": "https://github.com/buuug7",
    "npm": "https://npmjs.com/buuug7"
  }
}

### update soup

PUT http://localhost:3000/soups/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQyMTYyNDgsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIxMjY0OH0.7aQjbek_DdZXBOmYqj0QGRbOluYNp-1WCGYRLc7ApZ0

{
  "content": "such more useful clean my home"
}

### Delete the soup
DELETE http://localhost:3000/soups/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQyMTYyNDgsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIxMjY0OH0.7aQjbek_DdZXBOmYqj0QGRbOluYNp-1WCGYRLc7ApZ0

### star a soup
POST http://localhost:3000/soups/3/star
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQyMTYyNDgsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIxMjY0OH0.7aQjbek_DdZXBOmYqj0QGRbOluYNp-1WCGYRLc7ApZ0

### unstar a soup
POST http://localhost:3000/soups/3/unstar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQyMTYyNDgsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIxMjY0OH0.7aQjbek_DdZXBOmYqj0QGRbOluYNp-1WCGYRLc7ApZ0

### get soup star count
GET http://localhost:3000/soups/3/starcount
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjQyMTYyNDgsIm5hbWUiOiJidXV1ZzciLCJlbWFpbCI6InlvdXBwQDEyNi5jb20iLCJpZCI6MTEsImlhdCI6MTU2NDIxMjY0OH0.7aQjbek_DdZXBOmYqj0QGRbOluYNp-1WCGYRLc7ApZ0

###
