version: '3'
services:
  mysql:
    container_name: soup-hub-mysql
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soup_hub
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - webnet
  backend:
    container_name: soup-hub-backend
    depends_on:
      - mysql
    image: buuug7/soup-hub:1.0.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 3001:3001
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
