version: "3"
services:
  mysql:
    container_name: soup-hub-mysql
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soup_hub
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
